### ISSUE TITLE
is this lesson a code-along?

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/js-dom-and-events-window-onload-readme#1]
The lesson states that this is a code-along:
"This lesson doesn't render as a lab, but there are files within this repository you'll need to code along. Click on the Github icon in Learn, and fork and clone this repository."

However, there are no files in this repo to code along.

**Comment by drakeltheryuujin** [comment]
Hi @BrittanyTinnin,

This may be an issue with the Learn platform, and not with the files in the repo itself, however we will correct the README as well. This is an older lesson, so we've built this feedback into our next major release of this section of curriculum. We’re targeting delivery in the first half of 2019.
